---
train:

    params:
        batch_size: 32
        epoch: 80
        lr: 0.0005
        decay: 0.5
        decay_step: 60
        warmup: 5

    save:
        metapath: "/data/zhanglin/GazeCLIP/models/"
        folder: diap
        model_name: trans6
        step: 10

    data:
        image: "/data/zhanglin/Datasets/Gaze/EYEDIAP/Image"
        label: "/data/zhanglin/Datasets/Gaze/EYEDIAP/ClusterLabel"
        header: True
        name: diap
        isFolder: True

    pretrain:
        enable: True
        path: "/home/zhanglin/program/GazeCLIP/GazeTR-H-ETH.pt"
        device: 0

    device: 0

    reader: reader


test:

    load:
        begin_step: 30
        end_step: 80
        steps: 5

    data:
        image: "/data/zhanglin/Datasets/Gaze/EYEDIAP/Image"
        label: "/data/zhanglin/Datasets/Gaze/EYEDIAP/ClusterLabel"
        name: diap
        header: True
        isFolder: True

    savename: "evaluation"

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512

